# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  driver-backend

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        COGNITO_USER_POOOL_ID: us-east-1_G39FsYLeT
        TRACCAR_SECRET_NAME: arn:aws:secretsmanager:us-east-1:903002861645:secret:traccar-external-7SWVYA
        DRIVER_USER_TABLE: !Ref driverUserTable
        DEVICES_TABLE: DevicesIgnitionOff
        IPINFO_TOKEN: df58ccf730ab1c

Resources:
  mainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      VpcConfig:
        SecurityGroupIds:
          - sg-0218b58a60630dbf6
        SubnetIds:
          - subnet-033c1b8736acb59f9
      Policies:
        - AWSLambdaBasicExecutionRole
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  ignitionOffTimer:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: src/handlers/timer.ignitionOffTimer
      Runtime: nodejs14.x
      Policies:
        - AWSLambdaBasicExecutionRole
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Events:
        Scheduled:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  driverUserTable:
    Type: AWS::Serverless::SimpleTable
    TableName: driverUser


