# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  driver-backend

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        COGNITO_USER_POOOL_ID: us-east-1_LqgUs7jcx
        TRACCAR_SECRET_NAME: arn:aws:secretsmanager:us-east-1:959220416326:secret:traccar-yKvx0E
        DRIVER_USER_TABLE: !Ref driverUser

Resources:
  mainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
          ProxyApiGreedy:
            Type: Api
            Properties:
              Path: /{proxy+}
              Method: ANY
  driverUserTable:
    Type: AWS::Serverless::SimpleTable
    TableName: driverUser
