# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  driver-backend

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        COGNITO_USER_POOOL_ID: us-east-1_G39FsYLeT
        TRACCAR_SECRET_NAME: arn:aws:secretsmanager:us-east-1:903002861645:secret:traccar-external-7SWVYA
        DRIVER_USER_TABLE: !Ref driverUserTable
  Api:
    Cors:
      AllowMethods: "'POST, GET, OPTIONS, PUT, DELETE'"
      AllowHeaders: "'Content-Type, authorization'"
      # For example, "'X-Forwarded-For'". Checkout [HTTP Spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) for more details on the value
      AllowOrigin: "'*'"
      # For example, "'www.example.com'". Checkout [HTTP Spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) for more details on this value.
      MaxAge: "'2'"


Resources:
  mainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
          ProxyApiGreedy:
            Type: Api
            Properties:
              Path: /{proxy+}
              Method: ANY
  driverUserTable:
    Type: AWS::Serverless::SimpleTable
    TableName: driverUser
